apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-adminer
  template:
    metadata:
      labels:
        app: mysql-adminer
    spec:
      containers:
      - name: adminer
        image: adminer
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: adminer-service
spec:
  selector:
    app: mysql-adminer
  type: NodePort 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003
